name: Take screenshots and create PR

on:
  workflow_dispatch:

jobs:
  take-screenshots-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: 'gradle'

      - name: Install OptiPNG
        run: sudo apt install optipng

      - name: Setup Python dependencies for the screenshot server
        run: python -m pip install flask

      - name: Start screenshot server
        run: python ./app/src/androidTest/kotlin/org/zxkill/nori/screenshot/screenshot_server.py &

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: default
          arch: x86_64
          profile: Nexus 5X
          script: ./gradlew connectedCheck -P android.testInstrumentationRunnerArguments.class=org.zxkill.nori.screenshot.ScreenshotTakerTest

      - name: Print git status
        run: git status

      - name: Optimize PNGs
        run: optipng fastlane/metadata/android/**/images/phoneScreenshots/*.png

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: gh-action-update-screenshots
          title: "Update screenshots"
          body: "Automated changes by CI workflow \"Take screenshots and create Pull Request\""
          commit-message: "Update screenshots"
